# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

dist: trusty
sudo: false
language: nodejs

addons:
  firefox: latest
  chrome: stable

before_script:
  # Setup a virtual display for browser testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  # Mocha + Chai
  - cd mocha-chai && node banner.js
  - echo "travis_fold:start:SCRIPT folding starts"
  - npm install
  - echo "travis_fold:end:SCRIPT folding ends"
  - npm run mocha
  - npm run karma

  # Restlet
  - cd ../restlet && node banner.js

  # Postman
  - cd ../postman && node banner.js
  - echo "travis_fold:start:SCRIPT folding starts"
  - npm install --global newman
  - echo "travis_fold:end:SCRIPT folding ends"
  - newman run postman-collection.json --environment postman-environment.json

  # Stoplight
  - cd ../stoplight && node banner.js
  - curl https://raw.githubusercontent.com/stoplightio/prism/2.x/install.sh | sh
  - prism conduct /Users/james/Code/Personal/Training/super-powered-api-testing/Stoplight/stoplight-collection.json --spec "/Users/james/Code/Personal/Training/super-powered-api-testing/Stoplight/stoplight-spec.json" --env "API_ROOT=http://localhost:8080" --env "SLUG=supercoder"
