# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

dist: trusty
sudo: required

addons:
  firefox: latest
  chrome: stable

before_script:
  # Setup a virtual display for browser testing
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Install Node 8
  - nvm install 8
  - node --version
  - npm --version

script:
  # Mocha + Chai
  - cd mocha-chai && node banner.js
  - npm install
  - npm run mocha
  - npm run karma

  # Restlet
  - cd ../restlet && node banner.js

  # Postman
  - cd ../postman && node banner.js
  - npm install --global newman
  - newman run postman-collection.json --environment postman-environment.json

  # Stoplight
  - cd ../stoplight && node banner.js
  - sudo curl https://raw.githubusercontent.com/stoplightio/prism/2.x/install.sh | sudo sh
  - prism conduct stoplight-collection.json --spec stoplight-spec.json --env stoplight-environment.json
