# Jekyll configuration file
# https://jekyllrb.com/docs/configuration/

# https://github.com/pages-themes/primer
theme: jekyll-theme-primer

# Jekyll SEO Tag plugin
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md
title: Super-Powered API Testing
logo: /img/title-banner.png
author:
  name: James Messinger
  twitter: BigstickCarpet
twitter:
  username: BigstickCarpet
defaults:
  - scope:
      path: ""  # All pages
    values:
      image: /img/title-banner.png
