# AppVeyor Config
# http://www.appveyor.com/docs/lang/nodejs-iojs

image: Visual Studio 2017

environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version

  # Output version numbers, for debugging
  - node --version
  - npm --version

test_script:
  # Mocha + Chai
  - cd mocha-chai && node banner.js
  # - npm install
  # - npm run mocha
  # - npm run karma

  # Restlet
  - cd ../restlet && node banner.js

  # Postman
  - cd ../postman && node banner.js
  # - npm install --global newman
  # - newman run postman-collection.json --environment postman-environment.json

  # Stoplight
  - cd ../stoplight && node banner.js
  - curl -L "https://github.com/stoplightio/prism/releases/download/v2.0.0-beta.2/prism_windows_386.exe" > prism.exe
  - prism conduct stoplight-collection.json --spec stoplight-spec.json --env stoplight-environment.json

# Don't run MSBuild
build: off
