# AppVeyor Config
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output version numbers, for debugging
  - node --version
  - npm --version

  # Mocha + Chai
  - cd mocha-chai && node banner.js
  - npm install
  - npm run mocha
  - npm run karma

  # Restlet
  - cd ../restlet && node banner.js

  # Postman
  - cd ../postman && node banner.js
  - npm install --global newman
  - newman run postman-collection.json --environment postman-environment.json

  # Stoplight
  - cd ../stoplight && node banner.js
  #- curl https://raw.githubusercontent.com/stoplightio/prism/2.x/install.sh | sh
  #- prism conduct stoplight-collection.json --spec stoplight-spec.json --env stoplight-environment.json

# Don't run MSBuild
build: off
