# AppVeyor Config
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Mocha + Chai
  - cd mocha-chai && node banner.js
  - npm install
  - npm run mocha
  - npm run karma

  # Restlet
  - cd ../restlet && node banner.js

  # Postman
  - cd ../postman && node banner.js
  - npm install --global newman
  - newman run postman-collection.json --environment postman-environment.json

  # Stoplight
  #- cd ../stoplight && node banner.js
  #- curl https://raw.githubusercontent.com/stoplightio/prism/2.x/install.sh | sh
  #- prism conduct /Users/james/Code/Personal/Training/super-powered-api-testing/Stoplight/stoplight-collection.json --spec "/Users/james/Code/Personal/Training/super-powered-api-testing/Stoplight/stoplight-spec.json" --env "API_ROOT=http://localhost:8080" --env "SLUG=supercoder"

# Don't run MSBuild
build: off
